name: Build & Publish

on: push

env:
  PKG_NAME: restic
  DOCKER_USERNAME: steilerdev

# Required secrets:
# DOCKER_PWD            DockerHub password

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Package docker artifacts
      run: tar -C ./rootfs -czf ./rootfs.tar.gz ./
    - name: Upload docker artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rootfs
        path: ./rootfs.tar.gz

  publish-dockerhub:
    name: Publish Project to DockerHub
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: rootfs
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm,linux/arm64
        tags: ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}:latest
    - name: Update DockerHub readme
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
        repository: ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}
        readme-filepath: ./README.md
        short-description: ${{ github.event.repository.description }}